# -*- coding: utf-8 -*-
"""Cyber Safety/ Online dating code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsO3B8TsYAVAgh8KigmhTdO7_29_tolt

**1. IMPORT RAW DATA**

Upload survey_response_raw.csv here

cyber_risk (5 items): 1-5

loneliness (4 items): 1-4

social_support (4 items): 1-4

cyber_know (1 item): 1-5

gender: 0=male, 1=female, 2=other

year_in_school: Freshman = 1, Sophomore = 2, Junior = 3, Senior = 4, Graduate = 5, Other = 6

CSmajor: 0= Other majors, 1=Computer Science major

dating_apps: 0=No (no use of dating apps), 1=Yes (use any dating apps)
"""

import pandas as pd

file_id = "1cXIZ8gyLgYvHikaa7_UNm2XDiIZAMbYu"
url = f"https://drive.google.com/uc?id={file_id}"

df = pd.read_csv(url)



df.head()

"""**2. CLEAN + REFORMAT RAW DATA**"""

# Convert numeric columns to integer type
df = df.apply(pd.to_numeric, errors='ignore')
df = df.astype({col: 'Int64' for col in df.select_dtypes(include='number').columns})

df.head()

"""**3. CALCULATE MEAN**


"""

import pandas as pd

file_id = "1cXIZ8gyLgYvHikaa7_UNm2XDiIZAMbYu"
url = f"https://drive.google.com/uc?id={file_id}"
df = pd.read_csv(url)

df = df.apply(pd.to_numeric, errors='ignore')

cyber_risk_items = ['cyber_risk1', 'cyber_risk2', 'cyber_risk3', 'cyber_risk4', 'cyber_risk5']
loneliness_items = ['loneliness1', 'loneliness2', 'loneliness3', 'loneliness4']
social_support_items = ['social1', 'social2', 'social3', 'social4']
cyber_know_item = ['cyber_know']

variables = {
    "Cyber Risk": cyber_risk_items,
    "Loneliness": loneliness_items,
    "Social Support": social_support_items,
    "Cyber Knowledge": cyber_know_item
}

results = []

for var_name, cols in variables.items():
    if len(cols) > 1:
        mean_value = df[cols].mean(axis=1).mean()
    else:
        mean_value = df[cols[0]].mean()

    results.append([var_name, round(mean_value, 3)])

results_df = pd.DataFrame(results, columns=["Variable", "Mean"])
results_df

"""**4. CALCULATE STANDARD DEVIATION**"""

import pandas as pd

file_id = "1cXIZ8gyLgYvHikaa7_UNm2XDiIZAMbYu"
url = f"https://drive.google.com/uc?id={file_id}"
df = pd.read_csv(url)

df = df.apply(pd.to_numeric, errors='ignore')

cyber_risk_items = ['cyber_risk1', 'cyber_risk2', 'cyber_risk3', 'cyber_risk4', 'cyber_risk5']
loneliness_items = ['loneliness1', 'loneliness2', 'loneliness3', 'loneliness4']
social_support_items = ['social1', 'social2', 'social3', 'social4']
cyber_know_item = ['cyber_know']

variables = {
    "Cyber Risk": cyber_risk_items,
    "Loneliness": loneliness_items,
    "Social Support": social_support_items,
    "Cyber Knowledge": cyber_know_item
}

results = []

for var_name, cols in variables.items():

    if len(cols) > 1:
        participant_scores = df[cols].mean(axis=1)
        sd_value = participant_scores.std(ddof=1)
    else:
        sd_value = df[cols[0]].std(ddof=1)

    results.append([var_name, round(sd_value, 3)])

results_df = pd.DataFrame(results, columns=["Variable", "SD"])
results_df

"""**4. CALCULATE Z-SCORE**"""

import pandas as pd

file_id = "1cXIZ8gyLgYvHikaa7_UNm2XDiIZAMbYu"
url = f"https://drive.google.com/uc?id={file_id}"
df = pd.read_csv(url)

df = df.apply(pd.to_numeric, errors='ignore')

cyber_risk_items = ['cyber_risk1', 'cyber_risk2', 'cyber_risk3', 'cyber_risk4', 'cyber_risk5']
loneliness_items = ['loneliness1', 'loneliness2', 'loneliness3', 'loneliness4']
social_support_items = ['social1', 'social2', 'social3', 'social4']
cyber_know_item = ['cyber_know']

variables = {
    "Cyber Risk": cyber_risk_items,
    "Loneliness": loneliness_items,
    "Social Support": social_support_items,
    "Cyber Knowledge": cyber_know_item,
}

zscore_results = pd.DataFrame()

for var_name, cols in variables.items():

    if len(cols) > 1:
        scores = df[cols].mean(axis=1)
    else:
        scores = df[cols[0]]

    z_scores = (scores - scores.mean()) / scores.std(ddof=1)

    zscore_results[var_name + "_z"] = z_scores

zscore_results

"""**5. Merge z-score columns into main df**"""

df = pd.concat([df.reset_index(drop=True),
                zscore_results.reset_index(drop=True)],
               axis=1)

"""**6. Create CSmajor (0/1)**"""

import re

# Define keywords as REGEX patterns
cs_patterns = [
    r"\bcomputer science\b",
    r"\bdata science\b",
    r"\bcomputer information systems\b",
    r"\bcs\b"   # matches "CS", "CS & Econ", etc. but NOT "Economics"
]

def is_cs_major(major):
    major = str(major).lower()
    return int(any(re.search(pattern, major) for pattern in cs_patterns))

df['cs_major'] = df['major'].apply(is_cs_major)

"""**7. RUN LINEAR REGRESSION**"""

import statsmodels.api as sm

X = df[[
    "Loneliness_z",
    "Social Support_z",
    "Cyber Knowledge_z",
    "gender",
    "year_in_school",
    "cs_major"
]]

y = df["Cyber Risk_z"]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

print(model.summary())

"""**8. DRAW GRAPHS**"""

import matplotlib.pyplot as plt
import numpy as np

predictors = [
    ("Loneliness_z", "Loneliness (z)"),
    ("Social Support_z", "Social Support (z)"),
    ("Cyber Knowledge_z", "Cyber Knowledge (z)")
]

for col, label in predictors:
    x = df[col]
    y = df["Cyber Risk_z"]

    m, b = np.polyfit(x, y, 1)
    x_line = np.linspace(x.min(), x.max(), 100)
    y_line = m * x_line + b

    plt.figure()
    plt.scatter(x, y)
    plt.plot(x_line, y_line)
    plt.axhline(0, linestyle="--")
    plt.axvline(0, linestyle="--")
    plt.xlabel(label)
    plt.ylabel("Cyber Risk Behavior (z)")
    plt.title(f"{label} vs. Cyber Risk Behavior")
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))
df.boxplot(column="Cyber Risk_z", by="cs_major")

plt.xticks([1, 2], ["Non-CS Majors", "CS Majors"])
plt.xlabel("Major")
plt.ylabel("Cyber Risk Behavior (z)")
plt.title("Cyber Risk Behavior by Major")
plt.suptitle("")
plt.grid(False)
plt.show()

import statsmodels.api as sm

# Filter only CS majors
cs_df = df[df["cs_major"] == 1]

# Independent variables (use the exact names from your df)
X = cs_df[[
    "Loneliness_z",
    "Social Support_z",
    "Cyber Knowledge_z",
    "gender",
    "year_in_school"
]]

# Dependent variable (note the space in the name!)
y = cs_df["Cyber Risk_z"]

# Add intercept
X = sm.add_constant(X)

# Fit model
model_cs = sm.OLS(y, X).fit()

print(model_cs.summary())

# Filter not CS majors

noncs_df = df[df["cs_major"] == 0]

X_non = noncs_df[[
    "Loneliness_z",
    "Social Support_z",
    "Cyber Knowledge_z",
    "gender",
    "year_in_school"
]]

y_non = noncs_df["Cyber Risk_z"]

X_non = sm.add_constant(X_non)
model_noncs = sm.OLS(y_non, X_non).fit()

print(model_noncs.summary())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

sns.kdeplot(df[df["cs_major"]==0]["Cyber Risk_z"], label="Non-CS Majors")
sns.kdeplot(df[df["cs_major"]==1]["Cyber Risk_z"], label="CS Majors")

plt.title("Density Plot of Cyber Risk Behavior by Major")
plt.xlabel("Cyber Risk Behavior (z)")
plt.ylabel("Density")
plt.legend()
plt.show()

from scipy.stats import ttest_ind

cs     = df[df["cs_major"] == 1]
non_cs = df[df["cs_major"] == 0]

def ttest_and_print(var_name, pretty_label):
    cs_vals     = cs[var_name].dropna()
    non_vals    = non_cs[var_name].dropna()
    t_stat, p_val = ttest_ind(cs_vals, non_vals, equal_var=False)

    print(f"--- {pretty_label} ---")
    print(f"CS mean = {cs_vals.mean():.3f}, Non-CS mean = {non_vals.mean():.3f}")
    print(f"t({len(cs_vals)+len(non_vals)-2}) = {t_stat:.3f}, p = {p_val:.3f}")
    print()

#Cyber Risk (z)
ttest_and_print("Cyber Risk_z", "Cyber Risk Behavior (z)")

#Loneliness (z)
ttest_and_print("Loneliness_z", "Loneliness (z)")

#Social Support (z)
ttest_and_print("Social Support_z", "Social Support (z)")

#Cyber Knowledge (z)
ttest_and_print("Cyber Knowledge_z", "Cyber Knowledge (z)")